name: sketch_pad
description: An experimental redux of the DartPad UI.
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  collection: any
  dartpad_shared: any
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  intl4x: ^0.7.0
  messages: ^0.1.0
  fluttering_phrases: ^1.0.0
  go_router: ^13.0.0
  http: ^1.1.2
  json_annotation: ^4.8.1
  pointer_interceptor: ^0.10.0
  provider: ^6.1.0
  split_view: ^3.2.0
  url_launcher: ^6.2.2
  vtable: ^0.4.0
  web: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  test: any
  build_runner: 2.4.6
  build_runner_core: 7.2.10
  flutter_messages: ^0.3.0
  build_verify: ^3.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/dart_logo_128.png
    - assets/flutter_logo_192.png
    - lib/l10n/en.json
    - lib/l10n/de.json

dependency_overrides:
  dartpad_shared:
    path: ../dartpad_shared
